// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
//   TPs: [{type: 'autogenerated', dirName: '.'}],
  TP1: [{type: 'autogenerated', dirName: 'TP1'}],
  TP2: [{type: 'autogenerated', dirName: 'TP2'}],
  TP3: [{type: 'autogenerated', dirName: 'TP3'}],
  TP4: [{type: 'autogenerated', dirName: 'TP4'}],
  TP5: [{type: 'autogenerated', dirName: 'TP5'}],
  TP6: [{type: 'autogenerated', dirName: 'TP6'}],
  TP7: [{type: 'autogenerated', dirName: 'TP7'}],
  TP8: [{type: 'autogenerated', dirName: 'TP8'}],
};

module.exports = sidebars;
